### ISSUE TITLE
Single Decoder

### ISSUE THREAD

**Issue by BrianPugh** [xxlong0/ASNDepth#1]
Quick question (I didn't see this in the ablation study portion of your paper), did you guys experiment with a single decoder architecture and simply adding an additional output channel (1 for depth, 1 for guidance).

I'm a little confused by the decoder description in Section 4:
> The guidance feature encoder adopts a nearly identical structure with the depth encoder but without any feature reducing layers.

Shouldn't this sentence be referring to the decoders since they share an encoder? Or are you only taking certain feature maps from the encoder for the guidance decoder?

**Comment by xxlong0** [comment]
Thank your interest in our paper. We haven't done an experiment using only one decoder.  However, in my experience, since the guidance feature and depth feature are different, using two decoders should be better than using only one.

Sorry for the misunderstanding. It means that the depth decoder and guidance feature decoder have nearly the same structure, but the guidance feature decoder doesn't have any feature reducing layers.

**Comment by BrianPugh** [comment]
Do you have a more detailed diagram of your architecture (preferably with featuremap size)? It seems like the words "encoder" and "decoder" are used interchangeably in section 4 (Implementation).

> Our network adopts a multi-scale structure, which consists of one encoder and two decoders

Makes sense so far, this is consistent with figure 2.

> We use HRNet-48 [37] as our backbone

Still seems good; if we are treating this as our encoder, I'll assume the output featuremaps highlighted in blue are used.
![Screen Shot 2021-03-30 at 9 40 36 PM](https://user-images.githubusercontent.com/14318576/113091410-b147ce00-91a0-11eb-914d-99397f0b9ca6.png)


> Taking one image as input, one encoder produces coarse-to-fine estimated depths in four scales

So now the encoder is directly estimating depths? Or is it producing featuremaps at 4 scales (highlighted in blue in the hrnet image) to be used by the depth decoder? I'm assuming these have channels `[48, 96, 192, 384]`.

> , and the other decoder is used to generate the guidance feature map that captures geometric context.

Its confusing to mention the "other decoder" when the depth decoder hadn't been described.

> The depth estimation decoder consists of four blocks in different scales, each of which is constituted by two ResNet [12] basic blocks with a feature reducing convolution layer.

Is each scale from the encoder processed independently? Is each scale reduced to a single channel? Or to some intermediate feature size?

> The appending convolution layers are used to produce one-channel output for depth estimation.

Assuming that the outputs of each scale from above are bilinearly upsampled to the max resolution and concatenated and then passed through another 1x1 convolution?

>The guidance feature encoder adopts a nearly identical structure with the depth encoder but without any feature reducing layers.
Still confused since it wasn't clear what the feature reducing layers were in the depth decoder.

A detailed diagram of the architecture would greatly clear this up; thanks! Or, if the code is going to be released relatively soon, all my questions would be answered just by inspecting the code.

Thanks again! Super interesting approach with great results!

**Comment by flamehaze1115** [comment]
Thank you so much for pointing out these. Since our paper is finished in a rush, it contains some typos.
The codes are still messy, and I need some time to clean them. I will upload the model code first, and you can check the code.

**Comment by BrianPugh** [comment]
thanks!

**Comment by xxlong0** [comment]
The code of the network has been updated. Thanks.
