### ISSUE TITLE
Use of gt_depth for asn during training

### ISSUE THREAD

**Issue by BrianPugh** [xxlong0/ASNDepth#3]
I see in this portion of your code, you have the option of using the gt_depth as input to your asn module instead of the predicted depth by the network. Is this used? What technique is used in the results presented in the paper? thanks!

https://github.com/xxlong0/ASNDepth/blob/5f5316d15b65ab1f889da0f5f715edaa8ccaa0b5/model.py#L253

**Comment by flamehaze1115** [comment]
Hello. We don't use gt depth in the training. This option is just used for debugging, and we will update the complete codes soon.
